// const lodash = require('lodash')
const colors = require("colors");

exports.errorCatcher = (processCall) => processCall.stderr.on('data', (data) => {
    const dataFinal = data;
    console.log(colors.red('DETECTED ERROR: '))
    console.log(colors.yellow(dataFinal.toString().split('Error:')[1].split('\n')[0]));
});



// (node: 41137)  => another type of error headline generated by node